---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-2

filters:
  instance-state-name: running
  tag:Name: "vote-app-hagen*" # Matches all your instances
  # Group by Role tag → vote_result, redis_worker,"postgres-primary","postgres-standby"
keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""

  # Group by full Name tag
  - key: tags.Name
    prefix: ""
    separator: ""

  # Group by Availability Zone
  - key: placement.availability_zone
    prefix: az_
    separator: ""
